### ISSUE TITLE
خروجی اندروید برای خروج از ماتریکس🗿🗿🗿🗿🗿

### ISSUE THREAD

**Issue by amir1387aht** [ali77gh/Chap#3]
ایول داش با زبانت حال کردیم فقط خروجی اندروید لطف کن بزار میخوام مقایسه زبان چپ با فلاتر بزارم یوتیوب هم یکم پول بزنیم به جیب هم یکم گوگل رو فشاری کنیم هم یکم بخندیم

خلاصه ایول دا
خروجی وب هم تونستی هم که عالی میشه، با خروجی وب ماتریکس از ما خارج میشه🗿

**Comment by ali77gh** [comment]
ماتریکس همین الانش هم از ما خارج شده.

[Github link](https://github.com/ali77gh/ChapApp)
[Web Application](https://ali77gh.github.io/ChapApp/)

**Comment by amir1387aht** [comment]
impossible (┬┬﹏┬┬)

**Comment by hesam-init** [comment]
![Uploading 2024-05-18-201116_hyprshot.png…]()

**Comment by hesam-init** [comment]
![2024-05-18-201116_hyprshot](https://github.com/ali77gh/Chap/assets/89181937/80c8f527-3cf8-41d7-820c-d92e07f34f47)
